### ISSUE TITLE
MODEL_NAME is giving such kind of error.

### ISSUE THREAD

**Issue by tanaymitkari1** [Sentdex/pygta5#119]
NOTE : I am using this code in GTA san andreas 

Error in test_model.py

> WARNING:tensorflow:From C:\python3\lib\site-packages\tflearn\initializations.py:119: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
WARNING:tensorflow:From C:\python3\lib\site-packages\tflearn\objectives.py:66: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "D:\Projects\Artificial Intelligance\GTASDC\test_model.py", line 48, in <module>
    model.load(MODEL_NAME)
  File "C:\python3\lib\site-packages\tflearn\models\dnn.py", line 308, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "C:\python3\lib\site-packages\tflearn\helpers\trainer.py", line 490, in restore
    self.restorer.restore(self.session, model_file)
  File "C:\python3\lib\site-packages\tensorflow\python\training\saver.py", line 1538, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: D:\Projects\Artificial Intelligance\GTASDC\pygta5-car-fast-0.001-alexnetv2-10-epochs-300K-data.model

**Comment by abdesamie999** [comment]
Same , i have a problem for using a pre trained model .. (The passed save_path is not a valid checkpoint+project location )
