### ISSUE TITLE
Error when running test_model.py

### ISSUE THREAD

**Issue by zxzhijia** [Sentdex/pygta5#12]
Thank you for your code. I tried to run it. It shows me the error below. 

runfile('C:/Users/Xu Zhang/Desktop/pygta5-master/pygta5-master/Tutorial Codes/Part 8-13 code/test_model.py', wdir='C:/Users/Xu Zhang/Desktop/pygta5-master/pygta5-master/Tutorial Codes/Part 8-13 code')
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Traceback (most recent call last):

  File "<ipython-input-1-c9b6883ff730>", line 1, in <module>
    runfile('C:/Users/Xu Zhang/Desktop/pygta5-master/pygta5-master/Tutorial Codes/Part 8-13 code/test_model.py', wdir='C:/Users/Xu Zhang/Desktop/pygta5-master/pygta5-master/Tutorial Codes/Part 8-13 code')

  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Xu Zhang/Desktop/pygta5-master/pygta5-master/Tutorial Codes/Part 8-13 code/test_model.py", line 47, in <module>
    model = alexnet(WIDTH, HEIGHT, LR)

  File "C:\Users\Xu Zhang\Desktop\pygta5-master\pygta5-master\Tutorial Codes\Part 8-13 code\alexnet.py", line 40, in alexnet
    max_checkpoints=1, tensorboard_verbose=2, tensorboard_dir='log')

  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tflearn\models\dnn.py", line 64, in __init__
    best_val_accuracy=best_val_accuracy)

  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tflearn\helpers\trainer.py", line 167, in __init__
    self.session.run(init)

  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
    run_metadata_ptr)

  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
    feed_dict_string, options, run_metadata)

  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
    target_list, options, run_metadata)

  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)

ResourceExhaustedError: OOM when allocating tensor with shape[5120,4096]
	 [[Node: FullyConnected/W/Initializer/truncated_normal = Add[T=DT_FLOAT, _class=["loc:@FullyConnected/W"], _device="/job:localhost/replica:0/task:0/gpu:0"](FullyConnected/W/Initializer/truncated_normal/mul, FullyConnected/W/Initializer/truncated_normal/mean)]]

Caused by op 'FullyConnected/W/Initializer/truncated_normal', defined at:
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 227, in <module>
    main()
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 223, in main
    kernel.start()
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-c9b6883ff730>", line 1, in <module>
    runfile('C:/Users/Xu Zhang/Desktop/pygta5-master/pygta5-master/Tutorial Codes/Part 8-13 code/test_model.py', wdir='C:/Users/Xu Zhang/Desktop/pygta5-master/pygta5-master/Tutorial Codes/Part 8-13 code')
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/Xu Zhang/Desktop/pygta5-master/pygta5-master/Tutorial Codes/Part 8-13 code/test_model.py", line 47, in <module>
    model = alexnet(WIDTH, HEIGHT, LR)
  File "C:\Users\Xu Zhang\Desktop\pygta5-master\pygta5-master\Tutorial Codes\Part 8-13 code\alexnet.py", line 30, in alexnet
    network = fully_connected(network, 4096, activation='tanh')
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tflearn\layers\core.py", line 157, in fully_connected
    restore=restore)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tflearn\variables.py", line 65, in variable
    validate_shape=validate_shape)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 684, in _get_single_variable
    validate_shape=validate_shape)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variables.py", line 197, in __init__
    expected_shape=expected_shape)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variables.py", line 274, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 673, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\init_ops.py", line 239, in __call__
    dtype, seed=self.seed)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\random_ops.py", line 176, in truncated_normal
    value = math_ops.add(mul, mean_tensor, name=name)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 73, in add
    result = _op_def_lib.apply_op("Add", x=x, y=y, name=name)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\Xu Zhang\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[5120,4096]
	 [[Node: FullyConnected/W/Initializer/truncated_normal = Add[T=DT_FLOAT, _class=["loc:@FullyConnected/W"], _device="/job:localhost/replica:0/task:0/gpu:0"](FullyConnected/W/Initializer/truncated_normal/mul, FullyConnected/W/Initializer/truncated_normal/mean)]]

**Comment by Ghost---Shadow** [comment]
`ResourceExhaustedError` you need a bigger GPU

**Comment by zxzhijia** [comment]
@Ghost---Shadow I see. Thank you. Any recommendations? Titan is too expensive for me....$1400

**Comment by Ghost---Shadow** [comment]
Same here, use the smaller model provided or manually make it small until it fits in your GPU.

**Comment by Sentdex** [comment]
Buy the single best *used* GPU you can afford. You can find very lightly used GPUs on eBay. 

When you get the card, stress test it, either with a big network, or some specific stress testing software.

I buy most computer parts new since the used parts aren't much cheaper usually, but used GPUs are often 30-50%+ off.  You can get a maxwell titan x for $500-$600.

**Comment by Ghost---Shadow** [comment]
I implemented SqueezeNet. I am sure your graphics card can handle a 2MB model.
