### ISSUE TITLE
Help with final stages

### ISSUE THREAD

**Issue by Takachsin** [Sentdex/pygta5#14]
Hey Harrison,

I managed to get everything working up until the last step. I'm doing this on Windows like you. I had been using Python2 which doesn't support Tensorflow on Windows. So I switched to Python3 but now it says that Python3 doesn't support cv2. What did you use to get this to work?

**Comment by Takachsin** [comment]
Okay, well I got cv2 to install but something must still be a mess, when I run test_model.py I now get the following: (Everything up until now has run so smoothly =/ ) 

hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Scipy not supported!
2017-04-24 22:11:21.224247: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-04-24 22:11:21.224370: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-24 22:11:21.224644: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-24 22:11:21.225143: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-24 22:11:21.225539: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-24 22:11:21.225822: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-04-24 22:11:23.628458: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.630715: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.632295: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.633966: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.635665: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.637255: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.639717: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.641252: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.642860: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.644440: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.645924: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.647677: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.649591: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.651155: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.652752: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.654329: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.655879: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.657420: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.659685: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.661176: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.662983: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.664345: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.665901: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.667637: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.669806: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.671409: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.673003: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.674564: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.676102: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.678485: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.680170: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.681641: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.682915: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.684141: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.685435: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.687644: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.688906: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.690128: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
2017-04-24 22:11:23.691224: W c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:1152] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1039, in _do_call
    return fn(*args)
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _run_fn
    status, run_metadata)
  File "C:\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
         [[Node: save_1/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_2/tensor_names, save_1/RestoreV2_2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_model.py", line 32, in <module>
    model.load(MODEL_NAME)
  File "C:\Python35\lib\site-packages\tflearn\models\dnn.py", line 278, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "C:\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 449, in restore
    self.restorer.restore(self.session, model_file)
  File "C:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "C:\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
         [[Node: save_1/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_2/tensor_names, save_1/RestoreV2_2/shape_and_slices)]]

Caused by op 'save_1/RestoreV2_2', defined at:
  File "test_model.py", line 31, in <module>
    model = alexnet(WIDTH, HEIGHT, LR)
  File "C:\Users\Brad\Dropbox\Code\test-area\alexnet.py", line 38, in alexnet
    max_checkpoints=1, tensorboard_verbose=2, tensorboard_dir='log')
  File "C:\Python35\lib\site-packages\tflearn\models\dnn.py", line 64, in __init__
    best_val_accuracy=best_val_accuracy)
  File "C:\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 145, in __init__
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "C:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1056, in __init__
    self.build()
  File "C:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 691, in build
    restore_sequentially, reshape)
  File "C:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\Brad\Dropbox\Code\test-area\mariokart-0.001-alexnetv2-8-epochs.model
         [[Node: save_1/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_2/tensor_names, save_1/RestoreV2_2/shape_and_slices)]]
