### ISSUE TITLE
new collector error on startup

### ISSUE THREAD

**Issue by mechoriet** [Sentdex/pygta5#28]
got this error on startup of the collector
```python
File exists, loading previous data!
4
3
2
1
Traceback (most recent call last):
  File "D:\Development\python\pygta5\collecting-data-for-larger-fpv-model.py", line 109, in <module>
    main()
  File "D:\Development\python\pygta5\collecting-data-for-larger-fpv-model.py", line 85, in main
    screen = grab_screen(region=(0,40,800,640))
TypeError: grab_screen() got an unexpected keyword argument 'region'
````

**Comment by mechoriet** [comment]
changed the error to be more complete

**Comment by mechoriet** [comment]
can be closed
