### ISSUE TITLE
Tensorslicereader error

### ISSUE THREAD

**Issue by frossaren** [Sentdex/pygta5#40]
RESTART: C:\Users\gustav\Downloads\pygta5-master (1)\pygta5-master\test_model.py 
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Scipy not supported!
Traceback (most recent call last):
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1039, in _do_call
    return fn(*args)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _run_fn
    status, run_metadata)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\gustav\Downloads\pygta5-master (1)\pygta5-master\pygta5-car-fast-0.001-alexnetv2-10-epochs-300K-data.model
	 [[Node: save_1/RestoreV2_34 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_34/tensor_names, save_1/RestoreV2_34/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_34/_45 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_9_save_1/RestoreV2_34", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gustav\Downloads\pygta5-master (1)\pygta5-master\test_model.py", line 48, in <module>
    model.load(MODEL_NAME)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\models\dnn.py", line 282, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 452, in restore
    self.restorer.restore(self.session, model_file)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\gustav\Downloads\pygta5-master (1)\pygta5-master\pygta5-car-fast-0.001-alexnetv2-10-epochs-300K-data.model
	 [[Node: save_1/RestoreV2_34 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_34/tensor_names, save_1/RestoreV2_34/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_34/_45 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_9_save_1/RestoreV2_34", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'save_1/RestoreV2_34', defined at:
  File "<string>", line 1, in <module>
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\idlelib\run.py", line 130, in main
    ret = method(*args, **kwargs)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\idlelib\run.py", line 357, in runcode
    exec(code, self.locals)
  File "C:\Users\gustav\Downloads\pygta5-master (1)\pygta5-master\test_model.py", line 47, in <module>
    model = alexnet(WIDTH, HEIGHT, LR)
  File "C:\Users\gustav\Downloads\pygta5-master (1)\pygta5-master\alexnet.py", line 40, in alexnet
    max_checkpoints=1, tensorboard_verbose=0, tensorboard_dir='log')
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\models\dnn.py", line 64, in __init__
    best_val_accuracy=best_val_accuracy)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 147, in __init__
    allow_empty=True)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1056, in __init__
    self.build()
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 691, in build
    restore_sequentially, reshape)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\training\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\gustav\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for C:\Users\gustav\Downloads\pygta5-master (1)\pygta5-master\pygta5-car-fast-0.001-alexnetv2-10-epochs-300K-data.model
	 [[Node: save_1/RestoreV2_34 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_34/tensor_names, save_1/RestoreV2_34/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_34/_45 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_9_save_1/RestoreV2_34", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Dont know if i have done anything wrong or forgot something

**Comment by frossaren** [comment]
always get scipy and curses error in the beginning in some programs but they seems to work fine so i am guessing something else is wrong here

**Comment by frossaren** [comment]
have been looking through the error and found out first that the pygta5-car-fast... was saved by the code in the log directory. When i moved it out it found it but python doesnt have the right to open it...

**Comment by frossaren** [comment]
Starting to think that there is a problem with the training part. The shell restarts fast after i started the training leading me to think that it was done, but i have realized that 70k training samles doesnt go by that fast

**Comment by frossaren** [comment]
tried running train in powershell and got this error. Help pls



 c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:352] Loaded runtime CuDNN library: 6021 (compatibility version 6000) but source was compiled with 5105 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
2017-05-29 20:05:43.368253: F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\kernels\conv_ops.cc:659] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)
PS C:\Users\gustav\Downloads\pygta5-master\pygta5-master>

**Comment by frossaren** [comment]
Tried to install cudnn 5.1 instead of 6.0 and worked like a charm. Hope this helpes someone else too because it was daam lot of work to figure that out
