### ISSUE TITLE
Error when trying to train_model from new collector

### ISSUE THREAD

**Issue by mechoriet** [Sentdex/pygta5#41]
````python
hdf5 is not supported on this machine (please install/reinstall h5py for optimal experience)
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Scipy not supported!
---------------------------------
Run id: pygta5-car-fast-0.001-alexnetv2-10-epochs-300K-data.model
Log directory: log/
---------------------------------Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python35\lib\site-packages\tflearn\data_flow.py", line 187, in fill_feed_dict_queue
    data = self.retrieve_data(batch_ids)
  File "C:\Program Files\Python35\lib\site-packages\tflearn\data_flow.py", line 222, in retrieve_data
    utils.slice_array(self.feed_dict[key], batch_ids)
  File "C:\Program Files\Python35\lib\site-packages\tflearn\utils.py", line 187, in slice_array
    return X[start]
IndexError: index 7704 is out of bounds for axis 0 with size 400


Training samples: 8100
Validation samples: 2025
--
````
is this cause the train/alexnet is not ready for the new data?

**Comment by Sentdex** [comment]
New collector is for a much larger model with many more outputs. Use the create_training_data
