### ISSUE TITLE
curses is not supported on this machine error

### ISSUE THREAD

**Issue by tshrwbl** [Sentdex/pygta5#67]
Error on running train model.py
GPU Nvidia 930mx
supports cuda and tensor-flow
I'm too much confused by this error

curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\layers\recurrent.py", line 9, in <module>
    from tensorflow.python.ops.rnn import rnn_cell_impl as _rnn_cell, dynamic_rnn as _drnn, static_rnn as _rnn, bidirectional_dynamic_rnn as _brnn
ImportError: cannot import name 'rnn_cell_impl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asus\python code\gta5\train_model.py", line 4, in <module>
    from alexnet import alexnet
  File "C:\Users\asus\python code\gta5\alexnet.py", line 11, in <module>
    import tflearn
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\__init__.py", line 21, in <module>
    from .layers import normalization
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\layers\__init__.py", line 11, in <module>
    from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, \
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\layers\recurrent.py", line 13, in <module>
    from tensorflow.contrib.rnn.python.ops.core_rnn import static_rnn as _rnn, static_bidirectional_rnn as _brnn
ImportError: No module named 'tensorflow.contrib.rnn.python.ops.core_rnn'

**Comment by m4r1vs** [comment]
That curses are not supported is just a warning. It appears for every Windows user. The main error is the last line (ImportError).
I'd suggest you to check if TensorFlow and TFlearn are on latest version :)

**Comment by tshrwbl** [comment]
Using TensorFlow 1.2  TFlearn 3.2 
Tried on both Python 3.5.4 & 3.6.2,
still, it's not working.

>>> import tflearn
Traceback (most recent call last):
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\layers\recurrent.py", line 9, in <module>
    from tensorflow.python.ops.rnn import rnn_cell_impl as _rnn_cell, dynamic_rnn as _drnn, static_rnn as _rnn, bidirectional_dynamic_rnn as _brnn
ImportError: cannot import name 'rnn_cell_impl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    import tflearn
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\__init__.py", line 21, in <module>
    from .layers import normalization
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\layers\__init__.py", line 11, in <module>
    from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, \
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\layers\recurrent.py", line 13, in <module>
    from tensorflow.contrib.rnn.python.ops.core_rnn import static_rnn as _rnn, static_bidirectional_rnn as _brnn
ImportError: No module named 'tensorflow.contrib.rnn.python.ops.core_rnn'

**Comment by m4r1vs** [comment]
Seems like you need to have the bleeding edge version of TFlearn, the stable isn't compatible with all TensorFlow 1.2 features. Try pip install git+https://github.com/tflearn/tflearn.git

**Comment by tshrwbl** [comment]
Ok, I solved the version compatibility problem.
Python 3.5.4 TensorFlow 1.2 TFlearn 2.1
but got a new problem again  while running trainingdata.py 

```
`Traceback (most recent call last):
  File "C:\Users\asus\python code\gta5\train_model.py", line 4, in <module>
    from alexnet import alexnet
  File "C:\Users\asus\python code\gta5\alexnet.py", line 11, in <module>
    import tflearn
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\__init__.py", line 8, in <module>
    from . import models
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\models\__init__.py", line 2, in <module>
    from .dnn import DNN
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\models\dnn.py", line 5, in <module>
    from ..helpers.trainer import Trainer
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\helpers\__init__.py", line 2, in <module>
    from .evaluator import Evaluator
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\helpers\evaluator.py", line 9, in <module>
    from .trainer import evaluate_flow
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\helpers\trainer.py", line 9, in <module>
    from .. import callbacks
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\site-packages\tflearn\callbacks.py", line 3, in <module>
    import sys, curses
  File "C:\Users\asus\AppData\Local\Programs\Python\Python35\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ImportError: No module named '_curses'`
```

**Comment by Data-Scientist-Singh** [comment]
its because he used tenserflow 1.2 and the latest is 1.7 solved the issue for me might work for u as well

**Comment by rahulvansh66** [comment]
try to upgrade tensorflow & tflearn using the following...
pip3 install --upgrade tensorflow --user
pip install --upgrade tflearn
this works for me...

**Comment by t-varun** [comment]
`>>> import tflearn
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\VaruN\Desktop\tflearn-master\tflearn\__init__.py", line 62, in <module>
    from . import datasets
  File "C:\Users\VaruN\Desktop\tflearn-master\tflearn\datasets\__init__.py", line 1, in <module>
    from . import cifar10
  File "C:\Users\VaruN\Desktop\tflearn-master\tflearn\datasets\cifar10.py", line 16, in <module>
    from ..data_utils import to_categorical
  File "C:\Users\VaruN\Desktop\tflearn-master\tflearn\data_utils.py", line 7, in <module>
    from PIL import Image
  File "C:\Users\VaruN\Anaconda3\lib\site-packages\PIL\Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.`

**Comment by t-varun** [comment]
>>> import tflearn
curses is not supported on this machine (please install/reinstall curses for an optimal experience)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\VaruN\Desktop\tflearn-master\tflearn\__init__.py", line 62, in <module>
    from . import datasets
  File "C:\Users\VaruN\Desktop\tflearn-master\tflearn\datasets\__init__.py", line 1, in <module>
    from . import cifar10
  File "C:\Users\VaruN\Desktop\tflearn-master\tflearn\datasets\cifar10.py", line 16, in <module>
    from ..data_utils import to_categorical
  File "C:\Users\VaruN\Desktop\tflearn-master\tflearn\data_utils.py", line 7, in <module>
    from PIL import Image
  File "C:\Users\VaruN\Anaconda3\lib\site-packages\PIL\Image.py", line 60, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.

**Comment by t-varun** [comment]
I have upgraded all the llibraries to their stable versions. I am using 3.7 version of Python. Please tell me the solution for the above problem.

**Comment by b121** [comment]
> I have upgraded all the llibraries to their stable versions. I am using 3.7 version of Python. Please tell me the solution for the above problem.

Is tensorflow and all other basic libraries like pandas ,numpy working fine for python3.7

**Comment by t-varun** [comment]
> > I have upgraded all the llibraries to their stable versions. I am using 3.7 version of Python. Please tell me the solution for the above problem.
> 
> Is tensorflow and all other basic libraries like pandas ,numpy working fine for python3.7

Yes, all the other libraries are working fine.

**Comment by ashReal** [comment]
did you find solution

**Comment by utshomax** [comment]
If you are using windows , then just install windows-curses using pip.
pip install windows-curses

**Comment by cagridz** [comment]
> If you are using windows , then just install windows-curses using pip.
> pip install windows-curses



> If you are using windows , then just install windows-curses using pip.
> pip install windows-curses

It happened worse than old. there is no any action after wrote code

**Comment by rahuldazzler7** [comment]
use python 3.6.4 64bit , this resolved my issue of import error
