### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by Gooose1909** [Sentdex/pygta5#78]
File "F:\Python\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "F:\Python\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "F:\Python\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file F:\pygta5-master: Unknown: NewRandomAccessFile failed to Create/Open: F:\pygta5-master : Access is denied.

; Input/output error
	 [[Node: save_1/RestoreV2_176 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_176/tensor_names, save_1/RestoreV2_176/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_153/_87 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_564_save_1/RestoreV2_153", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\pygta5-master\train_model.py", line 49, in <module>
    model.load(PREV_MODEL)
  File "F:\Python\lib\site-packages\tflearn\models\dnn.py", line 308, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "F:\Python\lib\site-packages\tflearn\helpers\trainer.py", line 490, in restore
    self.restorer.restore(self.session, model_file)
  File "F:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "F:\Python\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "F:\Python\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "F:\Python\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "F:\Python\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file F:\pygta5-master: Unknown: NewRandomAccessFile failed to Create/Open: F:\pygta5-master : Access is denied.

; Input/output error
	 [[Node: save_1/RestoreV2_176 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_176/tensor_names, save_1/RestoreV2_176/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_153/_87 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_564_save_1/RestoreV2_153", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save_1/RestoreV2_176', defined at:
  File "<string>", line 1, in <module>
  File "F:\Python\lib\idlelib\run.py", line 142, in main
    ret = method(*args, **kwargs)
  File "F:\Python\lib\idlelib\run.py", line 457, in runcode
    exec(code, self.locals)
  File "F:\pygta5-master\train_model.py", line 46, in <module>
    model = googlenet(WIDTH, HEIGHT, 3, LR, output=9, model_name=MODEL_NAME)
  File "F:\pygta5-master\models.py", line 342, in inception_v3
    max_checkpoints=0, tensorboard_verbose=0,tensorboard_dir='log')
  File "F:\Python\lib\site-packages\tflearn\models\dnn.py", line 65, in __init__
    best_val_accuracy=best_val_accuracy)
  File "F:\Python\lib\site-packages\tflearn\helpers\trainer.py", line 147, in __init__
    allow_empty=True)
  File "F:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 1218, in __init__
    self.build()
  File "F:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "F:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "F:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "F:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "F:\Python\lib\site-packages\tensorflow\python\training\saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "F:\Python\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1020, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "F:\Python\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "F:\Python\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "F:\Python\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): Unable to open table file F:\pygta5-master: Unknown: NewRandomAccessFile failed to Create/Open: F:\pygta5-master : Access is denied.

; Input/output error
	 [[Node: save_1/RestoreV2_176 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_176/tensor_names, save_1/RestoreV2_176/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_153/_87 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_564_save_1/RestoreV2_153", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

whats happening here . I really dont understand Whats happening . Even i the location right but what am i missing here

**Comment by germanmarky** [comment]
Looks like you have LOAD_MODEL set to True, but no model to load.

If you haven't yet started training, change line 23 to False.

**Comment by Gooose1909** [comment]
I have my training data but still i get this .
i even deleted my data and trained again but i still get this

**Comment by germanmarky** [comment]
Have you ever ran the #2 file successfully?

If not, you have to change the LOAD_MODEL variable to False until you have a model to load.

**Comment by Gooose1909** [comment]
ok . Thanks
