### ISSUE TITLE
DataLossError ; Input/output error

### ISSUE THREAD

**Issue by justinkwan1216** [Sentdex/pygta5#80]
WARNING:tensorflow:From C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\initializations.py:119: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
Traceback (most recent call last):
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file C:\Users\jk-pc\Desktop\little_fighter_project\log\little-figter-2-0.001-alexnetv2-3-epochs.model: Unknown: NewRandomAccessFile failed to Create/Open: C:\Users\jk-pc\Desktop\little_fighter_project\log\little-figter-2-0.001-alexnetv2-3-epochs.model : �s���Q�ڡC

; Input/output error
	 [[Node: save_1/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_2/tensor_names, save_1/RestoreV2_2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/jk-pc/Desktop/little_fighter_project/test_model_3keys.py", line 61, in <module>
    model.load(MODEL_NAME)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\models\dnn.py", line 310, in load
    self.trainer.restore(model_file, weights_only, **optargs)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\helpers\trainer.py", line 490, in restore
    self.restorer.restore(self.session, model_file)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file C:\Users\jk-pc\Desktop\little_fighter_project\log\little-figter-2-0.001-alexnetv2-3-epochs.model: Unknown: NewRandomAccessFile failed to Create/Open: C:\Users\jk-pc\Desktop\little_fighter_project\log\little-figter-2-0.001-alexnetv2-3-epochs.model : �s���Q�ڡC

; Input/output error
	 [[Node: save_1/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_2/tensor_names, save_1/RestoreV2_2/shape_and_slices)]]

Caused by op 'save_1/RestoreV2_2', defined at:
  File "<string>", line 1, in <module>
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\idlelib\run.py", line 142, in main
    ret = method(*args, **kwargs)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\idlelib\run.py", line 460, in runcode
    exec(code, self.locals)
  File "C:/Users/jk-pc/Desktop/little_fighter_project/test_model_3keys.py", line 60, in <module>
    model = alexnet(WIDTH, HEIGHT, LR)
  File "C:/Users/jk-pc/Desktop/little_fighter_project\alexnet.py", line 42, in alexnet
    max_checkpoints=1, tensorboard_verbose=2, tensorboard_dir='log')
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\models\dnn.py", line 67, in __init__
    best_val_accuracy=best_val_accuracy)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tflearn\helpers\trainer.py", line 147, in __init__
    allow_empty=True)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1218, in __init__
    self.build()
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1020, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\Users\jk-pc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): Unable to open table file C:\Users\jk-pc\Desktop\little_fighter_project\log\little-figter-2-0.001-alexnetv2-3-epochs.model: Unknown: NewRandomAccessFile failed to Create/Open: C:\Users\jk-pc\Desktop\little_fighter_project\log\little-figter-2-0.001-alexnetv2-3-epochs.model : �s���Q�ڡC

; Input/output error
	 [[Node: save_1/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_2/tensor_names, save_1/RestoreV2_2/shape_and_slices)]]

what is really wrong here? I can't fix it

**Comment by JrFinch97** [comment]
I had the same problem.
I changed the Model Name to "anything" in train_model.py.
and LOAD_MODEL = False
and the file_name to the directory where the file of collected data is (included the file name of the file).

Hope this can help

**Comment by MacTavish-Soap** [comment]
> 

I ran into the same problem

but Im sorry I can understand your answers with my poor English

should you give me more details?
