### ISSUE TITLE
Can't create training data.

### ISSUE THREAD

**Issue by Flamin513** [Sentdex/pygta5#93]
Traceback (most recent call last):
  File "C:\Users\Gaming\Desktop\pygta5-master\collect_data.py", line 116, in <module>
    main(file_name, starting_value)
  File "C:\Users\Gaming\Desktop\pygta5-master\collect_data.py", line 97, in main
    np.save(file_name,training_data)
  File "C:\Users\Gaming\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numpy\lib\npyio.py", line 511, in save
    pickle_kwargs=pickle_kwargs)
  File "C:\Users\Gaming\AppData\Local\Programs\Python\Python36-32\lib\site-packages\numpy\lib\format.py", line 586, in write_array
    pickle.dump(array, fp, protocol=2, **pickle_kwargs)
MemoryError

Is it the python version im using?

**Comment by daniel-kukiela** [comment]
Last time I saw that error it was about insufficient memory (RAM).
32-bit version of Python might be a cause as well (process can allocate up to 4GB or memory iirc when running in 32-bit mode).

**Comment by Testdude3234** [comment]
Ah, I think I might be running 32 bit python, I'll upgrade to the 64 bit version and see if that fixes it.

**Comment by Data-Scientist-Singh** [comment]
u need to use python 3.6.2 64 bit otherwise tenserflow gives out  that error . it worked for me .

**Comment by Data-Scientist-Singh** [comment]
found another solution if it still creates problem its that u need to change the location where the data is going to be stored
